MAX_BATTERY_CHARGE_CURRENT = 60.0
MAX_BATTERY_DISCHARGE_CURRENT = 60.0

; NMC cell voltages
MAX_CELL_VOLTAGE = 4.10
MIN_CELL_VOLTAGE = 3.25
FLOAT_CELL_VOLTAGE = 4.07

; Cell voltage current limitation - MUST match NMC range
CCCM_CV_ENABLE = True
DCCM_CV_ENABLE = True
CELL_VOLTAGES_WHILE_CHARGING = 4.10, 4.05, 4.00, 3.90
MAX_CHARGE_CURRENT_CV_FRACTION = 0, 0.05, 0.5, 1
CELL_VOLTAGES_WHILE_DISCHARGING = 3.25, 3.30, 3.35, 3.45
MAX_DISCHARGE_CURRENT_CV_FRACTION = 0, 0.1, 0.5, 1

; monitoring
BATTERY_CELL_DATA_FORMAT = 1
GUI_PARAMETERS_SHOW_ADDITIONAL_INFO = True
SOC_CALCULATION = False

#SOC_CALCULATION = True
# to reset SOC to 100% when cell voltage reaches this value. This is needed if SOC_CALCULATION is True, and the battery is already fully charged when the system starts. The value should be slightly above FLOAT_CELL_VOLTAGE, but not too high to avoid resetting SOC to 100% when the battery is not fully charged.
#SOC_RESET_CELL_VOLTAGE = 3.7
SOC_RESET_CELL_VOLTAGE = 3.9


